/**
 * Builds sitemap.xml.
 *
 * It used to be a hand-maintained file in public/, with a test holding it in
 * step with the page map. That worked while every page was known in advance.
 * Articles are not: they arrive in the database between deploys, so the sitemap
 * has to be produced by the same build that renders them or it is wrong the
 * moment anything is published.
 *
 * There is now one source for the whole file — this function — and the test
 * checks it rather than a checked-in copy, so the two can no longer disagree.
 */

import { SITE_URL, SITEMAP_ROUTES } from "../src/lib/seo.js";

/**
 * How often each static page really changes, and how it ranks against the
 * others. Anything missing gets the default, which is the right answer for a
 * page nobody thought about.
 */
const STATIC_HINTS = {
  "/": { changefreq: "weekly", priority: "1.0" },
  "/pricing": { changefreq: "monthly", priority: "0.9" },
  "/inspiration": { changefreq: "weekly", priority: "0.7" },
  "/signup": { changefreq: "yearly", priority: "0.5" },
  "/privacy": { changefreq: "yearly", priority: "0.3" },
  "/terms": { changefreq: "yearly", priority: "0.3" },
};
const DEFAULT_HINT = { changefreq: "monthly", priority: "0.5" };

function escapeXml(value) {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function entry({ loc, lastmod, changefreq, priority }) {
  const lines = [`    <loc>${escapeXml(loc)}</loc>`];
  if (lastmod) lines.push(`    <lastmod>${escapeXml(lastmod)}</lastmod>`);
  if (changefreq) lines.push(`    <changefreq>${changefreq}</changefreq>`);
  if (priority) lines.push(`    <priority>${priority}</priority>`);
  return `  <url>\n${lines.join("\n")}\n  </url>`;
}

/** YYYY-MM-DD, which is all <lastmod> needs and all we can honestly claim. */
function day(iso) {
  if (!iso) return "";
  const date = new Date(iso);
  return Number.isNaN(date.getTime()) ? "" : date.toISOString().slice(0, 10);
}

/**
 * @param {object[]} posts published articles, newest first
 * @returns {string} the complete sitemap.xml
 */
export function buildSitemap(posts = []) {
  const urls = SITEMAP_ROUTES.map((route) => {
    const hint = STATIC_HINTS[route] || DEFAULT_HINT;
    // No <lastmod> on static pages on purpose. The only date this build knows
    // is the day it ran, which is not the day the page changed, and a sitemap
    // that claims every page changed on every deploy teaches a crawler to stop
    // believing the field. Articles below have a real one.
    return entry({ loc: route === "/" ? `${SITE_URL}/` : `${SITE_URL}${route}`, ...hint });
  });

  if (posts.length) {
    // The index earns a place once it has something on it.
    urls.push(entry({ loc: `${SITE_URL}/blog`, changefreq: "daily", priority: "0.8" }));
    for (const post of posts) {
      urls.push(
        entry({
          loc: `${SITE_URL}/blog/${post.slug}`,
          lastmod: day(post.updatedAt || post.publishedAt),
          changefreq: "monthly",
          priority: "0.6",
        })
      );
    }
  }

  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    "<!-- Generated by scripts/sitemap.mjs during the build. Public pages and",
    "     published articles only; signed-in routes and /login are excluded. -->",
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ...urls,
    "</urlset>",
    "",
  ].join("\n");
}
